### ISSUE TITLE
Lab 2

### ISSUE THREAD

**Issue by lasbio** [nstk24/BD-labs#2]
1. все файлы должны содержать комментарии. 
2.  Хорошим тоном является\ использование заглавных букв в командах sql. Например, в задании 1 - SELECT ... from..., а должно быть SELECT ... FROM....  И в других заданиях то же.
3. task 3 (и последующие)  - (а) в задании нет facid, (б) LIKE используется для текстовых полей 
4. task 5 - см п.3 +  условие " не превышающий" - <= , а не <
5. Task 6 - все поля вместо заданных по заданию "объекты" + неправильное условие (вместо T стоит t)
6. Task 7 - неправомерное использование LIKE, OR - не эффективно, лучше IN(....)
7. Task 8. Зачем 2 раза USE cd? Требуется выбрать в одном запросе. Нужны не все поля, а только пересиленны в задании (включая "качественная стоимость")
8. Task 9 - *
9. Task 11 - как различить какой ряд в возвращаемом результате относится к member, а какой к facility?
10. Task 12 - зачем LIMIT 1?
11. Task 13 - а откуда известно, что последние вступили именно '2012-09-26 18:08:45'? А если сейчас еще два вступят? Как быть?
12. Task 14 - условия заданы неправильно.

**Comment by nstk24** [comment]
вроде исправил и первую, и вторую

**Comment by lasbio** [comment]
2.3; 2.4; 2.5 - по условиям заданий надо отбирать только объекты.
2.8 - при использовании UNION достаточно задавать собственные названия колонок только в первом SELECT/
2.11 - по условиям задания должен в результирующей выборке должен быть  один столбец.

**Comment by lasbio** [comment]
1. Не выполнен пункт 1 задания ("сохранить в корне проекта") и пункт 5 ("Внесите файл создания базы данных в gitignore")
2. задание 10 - неправильно, в задании нет требования сортировки, т.е. надо отобрать первых 10 членов клуба. А у вас отобраны первые 10 по алфавиту.
3. задание 11 - "AS 'объект''" никак не используется. Можно убедиться прямым вычислением выборки.

**Comment by lasbio** [comment]
задание 10 - надо отобрать 10, отсортировать их по алфавиту. В вашем скрипте - отсортировано по алфавиту, потом отобрано 10.
задание 11 - не исправлено.
задание 14 - не верно. Отбор сделан не  по стоимости объекта, а по стоимости аренды гостем.

**Comment by nstk24** [comment]
Возможно в этот раз исправил 🤔

**Comment by lasbio** [comment]
10. Предположим удалены члены с memid in ( 3,5,7 ). Вернет ли Ваш скрипт 10 записей?

**Comment by nstk24** [comment]
исправил
